name: Deploy Sileo Repo

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dpkg-scanpackages
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev

    - name: Generate Packages file
      run: dpkg-scanpackages -m ./debs > Packages

    - name: Compress Packages file
      run: |
        bzip2 -fks Packages
        gzip -fk Packages

    - name: Create Release file
      run: |
        echo "Origin: 💫Axs pro✨" > Release
        echo "Label: 💫Axs pro✨" >> Release
        echo "Suite: stable" >> Release
        echo "Version: 1.0" >> Release
        echo "Codename: 💫Axs pro✨" >> Release
        echo "Architectures: iphoneos-arm64 iphoneos-arm64e" >> Release
        echo "Components: main" >> Release
        echo "Description: 自用插件分享，有问题请卸载！！！" >> Release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAT }}
        publish_dir: ./  # 部署整个仓库
