name: Update Packages on main

on:
  push:
    branches:
      - main
    paths:
      - 'debs/**'  # 监听 debs 目录下的文件变化

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dpkg-scanpackages
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev

    - name: Ensure script has execute permissions
      run: chmod +x ./generate_packages.sh

    - name: Run generate_packages.sh
      run: bash ./generate_packages.sh

    - name: Commit and push updated Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Packages Packages.bz2 Packages.gz Release
        git commit -m "Update Packages files"
        git push origin main

    - name: Create Release file
      run: |
        echo "Origin: 💫Axs pro✨" > Release
        echo "Label: 💫Axs pro✨" >> Release
        echo "Suite: stable" >> Release
        echo "Version: 1.0" >> Release
        echo "Codename: 💫Axs pro✨" >> Release
        echo "Architectures: iphoneos-arm64 iphoneos-arm64e" >> Release
        echo "Components: main" >> Release
        echo "Description: 自用插件分享，有问题请卸载！！！" >> Release
