name: Deploy Sileo Repo

on:
  push:
    branches: ["main"]
    paths:
      - 'debs/*.deb'  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dpkg-scanpackages
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev

    - name: Run generate_packages.sh
      run: bash ./generate_packages.sh

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PAT }}  # 使用个人访问令牌
        publish_dir: ./  # 部署整个仓库
